# Configurações do banco H2
spring.datasource.url=jdbc:h2:file:./data/hortapancsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurar log do SQL (opcional para deixar mais bonito)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Desativar página de erro branca do Spring
server.error.whitelabel.enabled=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
